filepaths:
  email-subscriptions: null

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_SENDER_LOGIN}
    password: ${EMAIL_SENDER_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 80